sb_admin:
    resource: "@fweberAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sb_templates:
    resource: "@fweberTemplateBundle/Resources/config/routing.yml"
    prefix:   /templates

sb_blog:
    resource: "@fweberBlogBundle/Resources/config/routing.yml"
    prefix:   /
