sb_api:
    resource: "@sbApiBundle/Resources/config/routing.yml"
    prefix:   /api

sb_admin:
    resource: "@sbAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sb_templates:
    resource: "@sbTemplateBundle/Resources/config/routing.yml"
    prefix:   /templates

sb_blog:
    resource: "@sbBlogBundle/Resources/config/routing.yml"
    prefix:   /
