security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        ajax_calls:
            pattern:    ^/_wdt
            anonymous:  ~
        login_firewall:
            pattern:    ^/admin/login$
            anonymous:  ~
        main:
            pattern:    ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   /admin/logout
                target: /

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
