services:
    template_controller:
        class:  "sb\TemplateBundle\Controller\TemplateController"
        calls:
            - [setContainer, ["@service_container"]]
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor