sb\DataBundle\Entity\Post:
    properties:
        title:
            - NotBlank: ~
        slug:
            - NotBlank: ~
        text:
            - NotBlank: ~
        creationDate:
            - DateTime: ~
        publishDate:
            - DateTime: ~
