admin_index:
    pattern:  /
    defaults: { _controller: sbAdminBundle:Page:index }

admin_dashboard:
    pattern:  /dashboard
    defaults: { _controller: sbAdminBundle:Page:dashboard }

admin_posts:
    resource: "@sbAdminBundle/Resources/config/Post/routing.yml"
    prefix:   /posts

admin_templates:
    resource: "@sbAdminBundle/Resources/config/Template/routing.yml"
    prefix:   /templates
