<?php

namespace sb\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{

    /**
     * Gets the currently activated Template
     *
     * @return \sb\DataBundle\Entity\Template
     */
    public function findCurrent()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder()
            ->add('select', 'h')
            ->add('from', 'sbDataBundle:TemplateHistory h')
            ->add('orderBy', 'h.id DESC')
            ->setMaxResults(1);
        $query = $qb->getQuery();

        $templateHistory = $query->getResult();

        return $templateHistory[0]->getTemplate();
    }

}
